version: "3.8"

services:
  siyuan:
    build:
      context: .
      dockerfile: Dockerfile
    image: siyuan_app
    container_name: siyuan_container
    ports:
      - "6800:6806"
    volumes:
      - ./data/:/home/siyuan/Documents/SiYuan/
    environment:
      - TZ=Europe/Moscow
      - RUN_IN_CONTAINER=true
    user: "1000:1000"
